#===============================================================================

project_name: btzar
runner_class: RRunner

#===============================================================================

base_params:

    full_output_dir_with_slash: $$output_path$$

    runset_name:   $$runset$$
    runset_abbrev: "First tests of bdpg and tzar under btzar"
    run_id:        $$run_id$$

    #--------------------

    single_action_using_tzar_reps: TRUE

#===============================================================================


