#===============================================================================

project_name: TestGen6basicVariants
runner_class: RRunner

#===============================================================================

libraries:

#---------------------------------------

    -  name: marxanLibrary

#       repo_type: local_file
#       url: file:////Users/bill/D/Marxan

       repo_type: http_zip
       url: http://glass.eres.rmit.edu.au/tzar_input/biodivprobgen/Marxan.zip
       download_mode: ONCE

#===============================================================================

base_params:

    full_output_dir_with_slash: $$output_path$$

        #---------------------------------
        #  Run identification parameters
        #---------------------------------

    runset_name:   $$runset$$
    runset_abbrev: "Test_gen_6"
    run_id:        $$run_id$$

        #  SET THIS VALUE EVERY TIME...
            #  Runset description to print in output since the runset name has
            #  to be short and tends to be cryptic.  The "|" should force the
            #  saved description string to include newlines in the string.
            #  If you don't want the newlines (i.e., you want one long string),
            #  then use a ">" in place of the "|".
    runset_description: |
        Nectar test example with 3 runs of 6 variants of a random Xu problem,
        random amount of error, all but slow network metrics, all reserve 
        selectors, gurobi time limited to marxan time.

    yaml_file_stored_as: "project.TestGen6basicVariants.2018-11-06-12-41.yaml"

    #---------------------------------------------------------------------------

    set_rand_seed_at_creation_of_all_new_major_objects: FALSE
#    bdpg_run_init_rand_seed: 1228514194

    integerize_string: "round"
    duplicate_links_allowed: FALSE    #TRUE

    #---------------------------------------------------------------------------
        #----------------------------------------
        #  Problem variants selector parameters
        #----------------------------------------

    gen_6_basic_variants: TRUE

        #--------------------------
        #  Error model parameters
        #--------------------------

    use_unif_rand_err_amt: TRUE
    err_amt_lower_bound: 0
    err_amt_upper_bound: 0.10

        #-------------------------------
        #  Reserve selector parameters
        #-------------------------------

    #---------------------------------------------------------------------------

    do_gurobi: TRUE

    use_given_time_as_limit: FALSE    #TRUE
    time_limit: 600    #  10 minutes (in seconds)  #  3600    #  1 hour (in seconds)
    use_marxan_time_as_limit: TRUE

    use_gap_limit: FALSE
    gap_limit: 0.005

    #---------------------------------------------------------------------------

    run_marxan: TRUE

        #  marxan control parameters
        #
        #  If marxan_use_default_input_parameters is TRUE, then all of these
        #  marxan_... parameters set in this file are ignored and marxan's
        #  default values are used instead.
        #  The one exception to this is the variable marxan_spf_const,
        #  which is a bit different from all the other parameters and is set
        #  in the just below the marxan_... parameters in this file.
    marxan_use_default_input_parameters: FALSE

    marxan_input_parameters_file_name: "$$library_path(marxanLibrary)$$input.dat"
    marxan_dir: "$$library_path(marxanLibrary)$$"
#    marxan_input_dir: "$$library_path(marxanLibrary)$$input/"
#    marxan_output_dir: "$$library_path(marxanLibrary)$$output/"
    marxan_pu_file_name: "pu.dat"
    marxan_spec_file_name: "spec.dat"
    marxan_puvspr_file_name: "puvspr.dat"
    marxan_runmode: 1
    marxan_heurtype: -1
    marxan_num_reps: 100
    marxan_num_iterations: "1000000"
#    marxan_num_iterations: "10000"
    marxan_spf_rule: "POWER_OF_10"

    #---------------------------------------------------------------------------

    do_simple_richness_forward: TRUE
    do_simple_richness_backward: TRUE

    #---------------------------------------------------------------------------

    do_unprotected_richness_forward: TRUE
    do_unprotected_richness_backward: TRUE

    #---------------------------------------------------------------------------

    do_zonation_like_forward: TRUE
    do_zonation_like_backward: TRUE

    #---------------------------------------------------------------------------

        #-----------------------------
        #  Network metric parameters
        #-----------------------------

    compute_network_metrics: TRUE    #  FALSE overrides all other network flags below

    compute_network_metrics_base_COR: TRUE
    compute_network_metrics_base_APP: TRUE
    compute_network_metrics_wrapped_COR: TRUE
    compute_network_metrics_wrapped_APP: TRUE

    use_igraph_metrics:    TRUE

    use_bipartite_metrics: TRUE
    bipartite_metrics_to_use: "all_except_slow_indices"    #  "quick_test"    #  "ALLBUTDD"

    #---------------------------------------------------------------------------

        #---------------------------------
        #  Xu problem control parameters
        #---------------------------------

    max_allowed_num_spp: 700  #2000
    num_prob_size_retries_allowed: 20

##                n__num_groups: 80
##                alpha__: 1.5
##                p__prop_of_links_between_groups: 1
##                r__density: 5

    use_unif_rand_alpha__: TRUE
    alpha___lower_bound: 0.2    #0
    alpha___upper_bound: 0.6    #1    #1.5

    use_unif_rand_n__num_groups: TRUE
    n__num_groups_lower_bound: 8    #2
    n__num_groups_upper_bound: 20    #15    #70

    use_unif_rand_r__density: TRUE
    r__density_lower_bound: 0.8    #0.01
    r__density_upper_bound: 3    #1.6    #3.0

    use_unif_rand_p__prop_of_links_between_groups: TRUE
    p__prop_of_links_between_groups_lower_bound: 0.14    #0.01
    p__prop_of_links_between_groups_upper_bound: 0.36    #0.99

        #-------------------------------
        #  Problem wrapping parameters
        #-------------------------------

    wrap_lognormal_dist_around_Xu: TRUE
    allow_imperfect_wrap: TRUE
    
#*******************************
        #  Temporary dummy inverse value until bug fix is committed and reverses this
#*******************************
    desired_Xu_spp_frac_of_all_spp: 0.75        #0.25    #0.5          #  <------- should allow random?
#*******************************
    
    solution_frac_of_landscape: 0.15    #0.3
    desired_max_abundance_frac: 0.7
    dep_set_PUs_eligible: FALSE
    add_one_to_lognormal_abundances: FALSE
    max_search_iterations: 500
    plot_rounded_abundances: TRUE

    #---------------------------------------------------------------------------

repetitions:
    generators:
        - key: cur_run_idx
          generator_type: linear_step
          start: 1
          step_size: 1
          count: 100

    #---------------------------------------------------------------------------


#===============================================================================

